name: Matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest,ubuntu-latest,windows-latest]
        node_version: [8,10,12,14]
      #fail-fast: true
      #max-parallel: 2
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log original node version
        run: node -v
      - name: Change node version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log modified node version
        run: node -v
